---
- name: deploy | prerequisites
  hosts: all
  become: yes
  become_user: newstap
  vars:
    site_dir: /home/newstap/www/newstap.com
  tasks:
    - name: create site folder (if needed)
      file:
        path: "{{ site_dir }}"
        state: directory

    - name: clone repo
      git:
        repo: "https://github.com/delameko/newstap.git"
        dest: "{{ site_dir }}"

